version: '3.8'

services:
  postgres-auth:
    image: postgres:15
    container_name: auth-db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-auth-data:/var/lib/postgresql/data
      - ./auth_service/db/init:/docker-entrypoint-initdb.d
    networks:
      - server-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d auth_db"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  auth-service:
    container_name: distributed-system-auth-service
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-auth:5432/auth_db?currentSchema=credential_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: credential_db
      SERVER_PORT: ${AUTH_SERVICE_PORT}
    ports:
      - "8080:8080"
    depends_on:
      postgres-auth:
        condition: service_healthy
    networks:
      - server-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`localhost`) && PathPrefix(`/auth`)"
      - "traefik.http.routers.auth.priority=10"
      - "traefik.http.services.auth.loadbalancer.server.port=8080"
      - "traefik.http.routers.auth.middlewares=cors-headers@docker"
    restart: unless-stopped

volumes:
  postgres-auth-data:

networks:
  server-network:
    driver: bridge
    name: server-network
