CREATE SCHEMA IF NOT EXISTS customer_db;
GRANT ALL ON SCHEMA customer_db TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA customer_db GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA customer_db GRANT ALL ON SEQUENCES TO postgres;

CREATE TABLE IF NOT EXISTS customer_db.question_answers (
    id BIGSERIAL PRIMARY KEY,
    question VARCHAR(500) NOT NULL,
    answer VARCHAR(2000) NOT NULL
);
